// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlAeHxxJavmP2rKKqsgTyZASIsGiB4l4',
    appId: '1:388724264620:web:48d1c585c699db2fdb9909',
    messagingSenderId: '388724264620',
    projectId: 'notes-706fd',
    authDomain: 'notes-706fd.firebaseapp.com',
    storageBucket: 'notes-706fd.firebasestorage.app',
    measurementId: 'G-D4M9BL6SP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-YCs884K7TIKJh0hr6G7NGqi9BihA5E',
    appId: '1:388724264620:android:ea46991c96597a37db9909',
    messagingSenderId: '388724264620',
    projectId: 'notes-706fd',
    storageBucket: 'notes-706fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOBM19dhcl5gr8Gwhgj1N6ghs1jwGnDT0',
    appId: '1:388724264620:ios:7bc817ac6f0188dadb9909',
    messagingSenderId: '388724264620',
    projectId: 'notes-706fd',
    storageBucket: 'notes-706fd.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOBM19dhcl5gr8Gwhgj1N6ghs1jwGnDT0',
    appId: '1:388724264620:ios:7bc817ac6f0188dadb9909',
    messagingSenderId: '388724264620',
    projectId: 'notes-706fd',
    storageBucket: 'notes-706fd.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMlAeHxxJavmP2rKKqsgTyZASIsGiB4l4',
    appId: '1:388724264620:web:ca5c3989b07ddf6edb9909',
    messagingSenderId: '388724264620',
    projectId: 'notes-706fd',
    authDomain: 'notes-706fd.firebaseapp.com',
    storageBucket: 'notes-706fd.firebasestorage.app',
    measurementId: 'G-WHDSHW9DLN',
  );

}