// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3GNUgyZGNdhHnDLjnA_0LU9_OHcnIkWE',
    appId: '1:763218510015:web:4e58ed510c7f91e774c60a',
    messagingSenderId: '763218510015',
    projectId: 'daftarbelanja-8f365',
    authDomain: 'daftarbelanja-8f365.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-8f365-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-8f365.firebasestorage.app',
    measurementId: 'G-H814QJYQH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_1NrIclRCRjCuw3qfOGdB6cZmeC5boo',
    appId: '1:763218510015:android:34bdd0d5e62e2b4974c60a',
    messagingSenderId: '763218510015',
    projectId: 'daftarbelanja-8f365',
    databaseURL: 'https://daftarbelanja-8f365-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-8f365.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3GNUgyZGNdhHnDLjnA_0LU9_OHcnIkWE',
    appId: '1:763218510015:web:d8e2e7348b19272174c60a',
    messagingSenderId: '763218510015',
    projectId: 'daftarbelanja-8f365',
    authDomain: 'daftarbelanja-8f365.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-8f365-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-8f365.firebasestorage.app',
    measurementId: 'G-1XC6P4B4JH',
  );
}
