// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgrtK4PagZpNW8Mz6upx5sWQtx8mJDrBg',
    appId: '1:352586746768:web:70db89dbfac96c807dc115',
    messagingSenderId: '352586746768',
    projectId: 'inventoris-barang',
    authDomain: 'inventoris-barang.firebaseapp.com',
    storageBucket: 'inventoris-barang.firebasestorage.app',
    measurementId: 'G-53VKGPDX7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMzhEWYNz5bpl4sKEph0nCynb8vVfhCBI',
    appId: '1:352586746768:android:cdc24197ccff6cbc7dc115',
    messagingSenderId: '352586746768',
    projectId: 'inventoris-barang',
    storageBucket: 'inventoris-barang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClu5a_gJxQRd7wBHkiPlm_J6o8g7AUziY',
    appId: '1:352586746768:ios:8be146c8daed16d37dc115',
    messagingSenderId: '352586746768',
    projectId: 'inventoris-barang',
    storageBucket: 'inventoris-barang.firebasestorage.app',
    iosBundleId: 'com.example.inventorisBarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClu5a_gJxQRd7wBHkiPlm_J6o8g7AUziY',
    appId: '1:352586746768:ios:8be146c8daed16d37dc115',
    messagingSenderId: '352586746768',
    projectId: 'inventoris-barang',
    storageBucket: 'inventoris-barang.firebasestorage.app',
    iosBundleId: 'com.example.inventorisBarang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgrtK4PagZpNW8Mz6upx5sWQtx8mJDrBg',
    appId: '1:352586746768:web:57fd0c71f4f915ee7dc115',
    messagingSenderId: '352586746768',
    projectId: 'inventoris-barang',
    authDomain: 'inventoris-barang.firebaseapp.com',
    storageBucket: 'inventoris-barang.firebasestorage.app',
    measurementId: 'G-ZMXDLGK2V4',
  );

}